### PR TITLE
[+] added huobi futures scraper

### PR DESCRIPTION
**Pull request by nazariyv**

### CODE REVIEW

**Comment by nazariyv** [comment]
I do not understand the folder structure in your project and I can't find any documentation. Will be happy to amend the PR if you give me more details. Also, would you like me to look at other exchanges? I can potentially nicely unify all of them.

**Comment by nazariyv** [comment]
I have noticed previous scrapers using this folder structure: https://github.com/diadata-org/diadata/pull/164/files

Do you want me to follow that project structure? Also, let me know if you would like me to implement other scrapers.

**Comment by kaythxbye** [comment]
This project structure would be ideal to use. Ideally, but them into exchange-scrapers and name them futures-<exchangename>. For additional tasks, please apply on Gitcoin and I'll approve you.

**Comment by nazariyv** [comment]
I will amend this PR soon, and as soon as payment clears, I will express interest in the other scrapers, writing out my plan to unify all of them nicely together.

**Comment by nazariyv** [comment]
@kaythxbye please do let me know if this is good to be merged now? Don't think I can fix the build issues since the master is failing too. + don't think I can configure the `APIScraper.go` since it pulls from the hidden dia. I have, nevertheless created an exportable `NewHuobiFuturesScraper.go` method that will spawn the scraping of all of the futures markets.

**Comment by nazariyv** [comment]
@kaythxbye hey, is there anything else that needs to be done. If not, when do you think you will be able to clear the payment, please?

**Comment by kaythxbye** [comment]
Sorry for the late reply, I'll integrate it today and clear payment.

**Comment by nazariyv** [comment]
I will apply for another scraper afterward and will work on these in a unified way

**Comment by nazariyv** [comment]
done a bunch of refactors here to make all of the futures scrapers more unified. Will update this PR when I will make the FTX one

**Comment by nazariyv** [comment]
closing this in favor of: https://github.com/diadata-org/diadata/pull/188

that PR includes the most recent Huobi implementation

**Pull request closed without merging**
