### PR TITLE
feat: MEXC scraper

### PR DESCRIPTION
**Pull request by top1st**
Added MEXC scraper

Screenshot_13

Let me know if there is something todo more.

### CODE REVIEW

**Comment by jppade** [comment]
@top1st Many thanks for the excellent contribution!
You seem to have found a websocket for trades which is great. I'd just like to understand in detail:

1. Which API version is this? I could not find the ws string in any of the documentations.
2. Are you sure the data is single trades level? At least the subscription has an "aggr" for probably aggregated in it.

Would be great if you could point me to the corresponding documentation.

**Comment by top1st** [comment]
@jppade there is no documentation of there site. I am a inspector and I analyze the raw transactions of websocket then write the project to integrate it.

**Comment by jppade** [comment]
@top1st Thanks for the quick reply. That's interesting. I am assuming you were using your browser's inspector in order to find the websocket connection.
Having said so I am assuming you don't know which API version this is, right?

**Comment by top1st** [comment]
@jppade  Yes I checked the documents but there is no websocket api and but despite of that while inspect the browser I was able to find they are using websocket. So I analyze it and used to integrate.

**Comment by jppade** [comment]
@top1st Got it - excellent job!
I'll review and get back to you / payout early next week.

**Pull request merged**
