### PR TITLE
Deribit scraper + FTX & Huobi (refactors)

### PR DESCRIPTION
**Pull request by nazariyv**
This PR includes:

1. Added `ScraperClose` and `Authenticate` methods to our futures interface. None of the other (FTX & Huobi) exchanges use authentication for the trade channel, so it is used as placeholder there. However, we do need authentication for Deribit.

2. An extra challenge in Deribit case was authentication and storing of the refresh token, which is required to make frequent websocket requests to keep the connection alive. These are made every 60 seconds, despite expiry being set at 900 seconds. This is to prevent websocket close, in case of Internet issues.

3. A method that makes a GET request (Deribit) to obtain all the futures markets and validate that the markets supplied by the user to scrape are valid.

4. An example of how to use the scraper in the comment section at the end of the Deribit file, shows how to use the scraper (same pattern as the other ones, with the addition of API keys that you need to supply).

@kaythxbye also feel free to close the previous FTX PR as it is now outdated.

### CODE REVIEW

**Comment by nazariyv** [comment]
@kaythxbye do you need the trades to be parsed into `dia.Trade`?

**Comment by nazariyv** [comment]
I can add that no problem if you would like.

**Comment by kaythxbye** [comment]
Not yet, the trades should be in another format:

```
type Option struct {
       Underlying  string
       Type        string
       DailyVolume float64
       Redemption  time.Time
}```

**Comment by nazariyv** [comment]
@kaythxbye 

1. Do you want the name `Option`? or `FuturesTrade`?
2. What are the possible values of `Type`?
3. Are you OK with the fact that `Redemption` and `DailyVolume` attributes will repeat most of the time and will cause you to store unnecessary repetitive information? An alternative solution could be to have a script that runs indefinitely and writes to a single file every day at midnight with your required information for ALL of the futures markets that we scrape? This will save you a ton of storage space.
4. When the contract is Perpetual, there is no redemption, should I set it to some date in the very far far away future?

**Comment by nazariyv** [comment]
@kaythxbye do you happen to have slack / telegram / whatsapp / email or anything else so that we can communicate a bit more promptly?

**Comment by kaythxbye** [comment]
Sure, my Telegram is @samuelbrack

________________________________
Von: Nazariy <notifications@github.com>
Gesendet: Montag, 2. Dezember 2019 12:15
An: diadata-org/diadata
Cc: kaythxbye; Mention
Betreff: Re: [diadata-org/diadata] Deribit scraper + FTX & Huobi (refactors) (#189) 

@kaythxbye do you happen to have slack / telegram / whatsapp / email or anything else so that we can communicate a bit more promptly?

**Comment by nazariyv** [comment]
latest work that includes this is in #190

**Pull request closed without merging**
