### PR TITLE
Futures contracts scrapers: Huobi (refactors) & FTX

### PR DESCRIPTION
**Pull request by nazariyv**
Hi,

This PR includes:

1. An interface for writers in `internal/pkg/scraper-writers/types.go` and a `FileWriter` struct that implements this interface. This struct is currently used to save the received messages from the WebSocket to a file. `FileWriter` works as follows:
                      

    - it calculates the `fileName` based on the `exchange` and `market` and gives us back the name of the file in the format: `yyyy-mm-dd-exchange-market.txt`.  This ensures that we are always writing to the correct file.

    - `FileWriter` will either create or append to the existing file: `os.O_APPEND|os.O_WRONLY|os.O_CREATE`. 

2. A `FuturesScraper` interface in `internal/pkg/exchange-scrapers/APIFuturesScraper.go`. This is a blueprint for our futures scrapers. 

    - Every scraper should be able to `Scrape` a single market. This is an atomic unit of self-contained work. I always prefer as simple code as possible without sacrificing the functionality. This method can respawn the WebSocket in case any error happens. We do this with the IIFE in a loop. This way, we do not have to worry about synchronizing the communication between the goroutines, since each goroutine is responsible for respawning itself. This makes them very robust and efficient.

    - Every scraper should be able to `ScrapeMarkets`. When instantiating the scraper (you have usage examples of each scraper at the bottom of the file in each of the respective scrapers. Let me know if you want me to create an example folder somewhere where I will move those commented blocks to, for convenience), you define the `Markets` you wish to scrape. `ScrapeMarkets` will then call our atomic `Scrape` workers (goroutines) that are self-contained. And this makes for a very robust scraping across the defined markets.

3. Refactors to the Huobi scraper (#187) as per the unified framework +  FTX Futures scraper implementation. Feel free to close that Huobi PR since it is outdated now.

If you approve the PR, I have a bunch of ideas on how to make all of this even better. So will be happy to get to work on the BitMex, Deribit, etc.

### CODE REVIEW

**Comment by nazariyv** [comment]
@kaythxbye please, have a look when you have time. Thanks!

**Comment by nazariyv** [comment]
@kaythxbye I have added marshaling of the message to get the type out of it so that we do not write the pong and subscription messages. The file is now clean just with the trades.

**Comment by kaythxbye** [comment]
Thanks, accepted the bounty! Great work here.

**Comment by nazariyv** [comment]
closing this in favor of the new PR, which has this PR and more features & improvements.
the latest work (as of 12/02/2019) is on PR: #189

**Pull request closed without merging**
