### PR TITLE
ETC supply scraper added

### LINKED ISSUE #122: ETC Blockchain Scraper
Implement a Ethereum Classic Blockchain scraper reporting the amount of circulating ETC coins using our Go framework. Detailed documentation and examples can be found at https://github.com/diadata-org/diadata/blob/master/documentation/methodology/SupplyNumbers.md

### PR DESCRIPTION
**Pull request by mestorlx**
This PR closes #122

### CODE REVIEW

**Comment by mestorlx** [comment]
Its because the node have not retrieve any block yet. That error will disappear as soon as the first node is retrieved. So you want me to add a sleep?

**Comment by frranck** [comment]
yes, please add a sleep and change it to a warning, maybe would be a good idea to write that this is normal if the blockchain is synching ?

**Comment by mestorlx** [comment]
@frranck Updated. The error message will be shown if the ETC node is not running or can not be reached. Basically it is a message that the RPC port is not reachable.

**Comment by frranck** [comment]
Ok thanks, it's synching ATM...

**Comment by mestorlx** [comment]
Any issue that needs to be addressed before it can be merged?
@kaythxbye

**Pull request merged**
