### PR TITLE
add nuo network scrapper

### LINKED ISSUE #233: Defi Lending Rate Scraper for Nuo Network
Your job is to source and connect the Nuo Network lending protocol, sourcing lending rates, volume, and other data, pushing it into our database for open-source usage.

Task: Source primary data defined below for connectivity to our database for:

- Lending Rate
- DeFi Total Value Locked (USD)
- Total ETH locked
- Underlying Blockchain
- Protocol token (if applicable)

Please commit a scraper which ideally also scrapes historical data as much as possible.
Tutorial on data format: https://docs.diadata.org/documentation/tutorials/write-your-own-defi-lending-rate-scraper

In case you need to extend the data model, you should also include it into your commit.

A concrete similar example on the data set to source https://defipulse.com/.

### PR DESCRIPTION
**Pull request by iamonuwa**
Closes #233

### CODE REVIEW

**Comment by jppade** [comment]
@iamonuwa Thanks for the PR! Please have a look whether you can implement the UpdateState method as well by using the addresses of USDc and ETH resp., such as done here:
https://github.com/diadata-org/diadata/blob/master/internal/pkg/defiscrapers/updateCompound.go
The same goes for the instadapp scraper.

**Comment by jppade** [comment]
@iamonuwa Thanks for the new PR. Looks a lot better! However, there is still one issue: The scrapers (nuo and instadapp) are not scraping any data. Are you sure the json fields are compliant with the representation on thegraph?
It would be great, if you could have a look into that.

**Comment by iamonuwa** [comment]
> @iamonuwa Thanks for the new PR. Looks a lot better! However, there is still one issue: The scrapers (nuo and instadapp) are not scraping any data. Are you sure the json fields are compliant with the representation on thegraph?
> It would be great, if you could have a look into that.

Sure, I'll update the app now

**Comment by iamonuwa** [comment]
@jppade the json fields conform with thegraph query representation. However, I can rewrite the structs to conform with thegraph. Not sure if it will conform with the app

**Pull request closed without merging**
